version: "3.4"

networks:
  net1:

services:

  postgres:
    image: "aldycool/postgres-wal-g:14.4"
    restart: unless-stopped
    networks:
      - net1
    volumes:
      - /root/mount/postgres:/var/lib/postgresql/data
      - /root/mount/wal-g:/var/lib/postgresql/wal-g-data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=secretpass
      - WALG_FILE_PREFIX=/var/lib/postgresql/wal-g-data

  pgadmin:
    image: "dpage/pgadmin4:6.11"
    restart: unless-stopped
    networks:
      - net1
    volumes:
      - /root/mount/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=secretpass
    ports:
      - "15432:80"
    depends_on:
      - postgres