apiVersion: v1
kind: Namespace
metadata:
  name: pg-restore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-postgres-pvc
  namespace: pg-restore
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: restore-test
  namespace: pg-restore
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  volumes:
    - name: vol-postgresql
      persistentVolumeClaim:
        claimName: restore-postgres-pvc
  containers:
    - name: postgres-wal-g-setup
      image: aldycool/postgres-wal-g:14.4
      volumeMounts:
        - name: vol-postgresql
          mountPath: /var/lib/postgresql
      env:
        - name: PGDATA
          value: "/var/lib/postgresql/data"
      command: ["/bin/sh"]
      args:
        - -c
        - >-
          echo "Finished!" &&
          trap : TERM INT; sleep 9999999999d & wait
